# Usa un'immagine di Node.js
FROM node:18

# Imposta la cartella di lavoro
WORKDIR /usr/src/app

# Copia package.json e package-lock.json
COPY package*.json ./

# Installa le dipendenze normali e quelle di sviluppo
RUN npm install

# Installa nodemon a livello globale
RUN npm install -g nodemon

# Copia il codice sorgente
COPY . .

# Espone la porta dell'app
EXPOSE 8080

# Comando per avviare Nodemon in modalità dev
CMD ["npm", "run", "dev"]
