services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: login-signup-project
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: ${DB_HOST}
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql/
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
  db-data: