services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql-container
    networks:
      - my-network 

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network 

networks:
  my-network:

volumes:
  mysql-data:
